### ISSUE TITLE
`==` is not defined for `IntervalUnion`

### ISSUE THREAD

**Issue by abraunst** [AnderGray/IntervalUnionArithmetic.jl#17]
```julia
julia> using IntervalUnionArithmetic
julia> intervalUnion(1,2) == Interval(1,2) ∪ ∅
false

julia> intervalUnion(1,2) == ∅
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Vector{Interval{Float64}}
Closest candidates are:
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray at ~/src/julia/build1.7/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:58
...
```

**Comment by abraunst** [comment]
another function that is not defined but could be is `isempty`

**Comment by AnderGray** [comment]
Thanks for spotting this and raising the issue! PR #18 has been opened

I think the desired functionality is added. But this also returns true:

```julia
julia> intervalUnion(1, 2) == interval(1, 2)
true

```

I think it's fine, but perhaps we don't want it?

**Comment by abraunst** [comment]
Wow, that was fast! Thank you so much for this. I also think that it's perfect to have a well defined equality between `IntervalUnion` and `Interval` :)
